export const ADD_POSTS = "ADD_POSTS";
export const ADD_POST = "ADD_POST";
export const POSTS_LOADING = "POSTS_LOADING";
export const POSTS_FAILED = "POSTS_FAILED";
export const DELETE_POST = "DELETE_POST";

export const ADD_LIKES = "ADD_LIKES";
export const ADD_LIKE = "ADD_LIKE";
export const LIKES_FAILED = "LIKES_FAILED";

export const ADD_RECIPES = "ADD_RECIPES";
export const ADD_RECIPE = "ADD_RECIPE";
export const RECIPES_FAILED = "RECIPES_FAILED";
export const RECIPES_LOADING = "RECIPES_LOADING";

export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const FAVORITES_FAILED = "FAVORITES_FAILED";
export const ADD_FAVORITES = "ADD_FAVORITES";

export const ADD_MEALTYPES = "ADD_MEALTYPES";

export const ADD_USERINFO = "ADD_USERINFO";

export const ADD_USER_MEALPLAN = "ADD_USER_MEALPLAN";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
